import React from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, BarChart3, BellRing, CheckCircle2, FileSearch, Map, ShieldCheck, Sparkles } from 'lucide-react'
import { projects, money } from '../data'
export default function Home(){
  const total=projects.reduce((a,p)=>a+p.sanctioned,0), util=projects.reduce((a,p)=>a+p.utilized,0)
  return <div className="min-h-screen bg-white">
    <header className="border-b border-slate-200 bg-white"><div className="max-w-7xl mx-auto px-5 h-16 flex items-center justify-between"><Link to="/" className="flex items-center gap-3"><div className="h-10 w-10 bg-navy text-white rounded-xl flex items-center justify-center"><ShieldCheck/></div><div><b>MPLADS Insight</b><div className="text-[10px] text-slate-500">Project Monitoring & Risk Intelligence</div></div></Link><div className="flex gap-2"><Link to="/dashboard" className="btn-secondary">Public Dashboard</Link><Link to="/login" className="btn-primary">Login <ArrowRight size={15}/></Link></div></div></header>
    <section className="bg-gradient-to-br from-[#082f57] to-[#0d4c86] text-white"><div className="max-w-7xl mx-auto px-5 py-20 md:py-24 grid md:grid-cols-2 gap-12 items-center"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 border border-white/20 px-3 py-1 text-xs font-semibold mb-5"><Sparkles size={14}/> AI-assisted monitoring layer</div><h1 className="text-4xl md:text-6xl font-extrabold leading-tight">From project data to <span className="text-blue-200">actionable oversight.</span></h1><p className="text-blue-100 mt-5 max-w-xl leading-7">A modern monitoring workspace for tracking MPLADS projects, financial utilization, physical progress, geographic spread and emerging risk signals.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/dashboard" className="btn bg-white text-navy hover:bg-blue-50">Explore Dashboard <ArrowRight size={16}/></Link><Link to="/projects" className="btn bg-white/10 border border-white/20 text-white">Browse Projects</Link></div></div><div className="card bg-white/10 border-white/20 p-5 backdrop-blur"><div className="text-sm text-blue-100 mb-4">Live-style demo snapshot</div><div className="grid grid-cols-2 gap-3">{[['Projects',projects.length],['High risk',projects.filter(p=>p.risk==='High').length],['Sanctioned',money(total)],['Utilized',money(util)]].map(x=><div key={x[0]} className="rounded-xl bg-white/10 p-4"><div className="text-xs text-blue-100">{x[0]}</div><div className="text-xl font-extrabold mt-1">{x[1]}</div></div>)}</div><div className="mt-4 rounded-xl bg-white p-4 text-slate-800"><div className="flex justify-between text-sm"><span>Overall utilization</span><b>{Math.round(util/total*100)}%</b></div><div className="h-2 bg-slate-100 rounded-full mt-2"><div className="h-full bg-navy rounded-full" style={{width:`${util/total*100}%`}}/></div></div></div></div></section>
    <section className="max-w-7xl mx-auto px-5 py-16"><div className="text-center max-w-2xl mx-auto"><div className="eyebrow">What the platform adds</div><h2 className="text-3xl font-extrabold mt-2">More than a data portal</h2><p className="text-slate-500 mt-3">Designed as an intelligence and workflow layer over project information—not a replacement for official systems.</p></div><div className="grid md:grid-cols-3 gap-5 mt-10">{[[BarChart3,'Decision dashboard','Turn scattered project indicators into one operational view.'],[BellRing,'Early risk alerts','Surface delays, progress mismatches and utilization patterns for review.'],[Map,'Geographic intelligence','Understand project concentration and risk across states and districts.'],[FileSearch,'Project 360°','See financial, physical, timeline and agency information together.'],[CheckCircle2,'Review workflow','Keep human verification and official decision-making in the loop.'],[ShieldCheck,'Trust & governance','Clearly label AI outputs as advisory with audit-ready design principles.']].map(([I,t,d])=><div className="card p-6" key={t}><div className="h-11 w-11 rounded-xl bg-blue-50 text-navy flex items-center justify-center"><I/></div><h3 className="font-bold mt-4">{t}</h3><p className="text-sm text-slate-500 mt-2 leading-6">{d}</p></div>)}</div></section>
    <footer className="border-t border-slate-200"><div className="max-w-7xl mx-auto px-5 py-7 text-sm text-slate-500 flex flex-wrap justify-between gap-3"><span>© 2026 MPLADS Insight — SIH prototype</span><span>Demo data only • Not an official Government of India portal</span></div></footer>
  </div>
}