"""
Routes for AI Shield alerts.

Alerts are derived from the current Phase 7 Risk Fusion output:
    backend/data/processed/project_risk_scores.csv

The CSV is the source of truth for AI risk. Project metadata is still
read from the Project table when needed, but legacy Phase-2 risk columns
are NOT used to generate alerts.

Alerts are advisory review-priority signals, not confirmations of fraud.
"""

from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import List

import pandas as pd
from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.auth import get_current_user
from app.database import get_db
from app.models import Project
from app.schemas import AlertOut

router = APIRouter(
    prefix="/alerts",
    tags=["alerts"],
    dependencies=[Depends(get_current_user)],
)

# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

BACKEND_ROOT = Path(__file__).resolve().parents[2]
RISK_OUTPUT_PATH = BACKEND_ROOT / "data" / "processed" / "project_risk_scores.csv"


# ---------------------------------------------------------------------
# Current Risk Fusion domains
# ---------------------------------------------------------------------

CONTRIBUTION_FIELDS = [
    ("compliance_contribution", "compliance_risk", "Compliance"),
    ("financial_anomaly_contribution", "financial_anomaly", "Financial anomaly"),
    ("timeline_anomaly_contribution", "timeline_anomaly", "Timeline anomaly"),
    ("duplicate_contribution", "duplicate_signal", "Duplicate similarity"),
    ("data_quality_contribution", "data_quality", "Data quality"),
    ("payment_contribution", "payment_pattern", "Payment pattern"),
    ("isolation_forest_contribution", "isolation_forest", "Isolation Forest"),
]

# Contribution caps from ml/risk_config.py.
CONTRIBUTION_CAPS = {
    "compliance_contribution": Decimal("28"),
    "financial_anomaly_contribution": Decimal("20"),
    "timeline_anomaly_contribution": Decimal("12"),
    "duplicate_contribution": Decimal("12"),
    "data_quality_contribution": Decimal("8"),
    "payment_contribution": Decimal("10"),
    "isolation_forest_contribution": Decimal("10"),
}

SEVERITY_PRIORITY = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
}


# ---------------------------------------------------------------------
# CSV loader
# ---------------------------------------------------------------------

def _load_risk_fusion() -> pd.DataFrame:
    """
    Load the production Phase 7 Risk Fusion output.

    This file is generated by:
        python -m ml.risk

    The API deliberately reads the generated production artifact
    instead of rebuilding risk scores independently.
    """
    if not RISK_OUTPUT_PATH.exists():
        raise RuntimeError(
            f"Risk Fusion output not found: {RISK_OUTPUT_PATH}. "
            "Run `python -m ml.risk` first."
        )

    df = pd.read_csv(RISK_OUTPUT_PATH)

    required_columns = {
        "work_id",
        "risk_score",
        "risk_level",
        "evidence_status",
        "compliance_contribution",
        "financial_anomaly_contribution",
        "timeline_anomaly_contribution",
        "duplicate_contribution",
        "data_quality_contribution",
        "payment_contribution",
        "isolation_forest_contribution",
        "total_evidence_signals",
        "high_severity_signal_count",
        "medium_severity_signal_count",
        "low_severity_signal_count",
        "has_compliance_signal",
        "has_financial_anomaly",
        "has_timeline_anomaly",
        "has_duplicate_signal",
        "has_data_quality_signal",
        "has_payment_signal",
        "has_isolation_forest_signal",
        "top_reason_1",
        "top_reason_2",
        "top_reason_3",
        "risk_reasons",
        "source_signal_summary",
    }

    missing = required_columns - set(df.columns)

    if missing:
        raise RuntimeError(
            "Risk Fusion output is missing required columns: "
            + ", ".join(sorted(missing))
        )

    df["work_id"] = df["work_id"].astype(str)

    return df


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

def _decimal(value) -> Decimal:
    """Safely convert a numeric CSV value to Decimal."""
    if pd.isna(value):
        return Decimal("0")

    try:
        return Decimal(str(value))
    except Exception:
        return Decimal("0")


def _is_true(value) -> bool:
    """Handle boolean values loaded from CSV."""
    if isinstance(value, bool):
        return value

    if pd.isna(value):
        return False

    return str(value).strip().lower() in {
        "true",
        "1",
        "yes",
    }


def _risk_level_severity(risk_level: str) -> str:
    """Map Risk Fusion level directly to alert severity."""
    level = (risk_level or "").upper()

    if level == "CRITICAL":
        return "critical"

    if level == "HIGH":
        return "high"

    if level == "MEDIUM":
        return "medium"

    return "low"


def _build_reasons(row: pd.Series) -> List[str]:
    """
    Prefer the reasons generated by Risk Fusion itself.
    Fall back to top_reason_1/2/3 if risk_reasons is empty.
    """
    reasons = []

    risk_reasons = row.get("risk_reasons")

    if pd.notna(risk_reasons):
        text = str(risk_reasons).strip()

        if text and text.lower() not in {"nan", "none", "[]"}:
            reasons.append(text)

    if not reasons:
        for field in ("top_reason_1", "top_reason_2", "top_reason_3"):
            value = row.get(field)

            if pd.notna(value):
                text = str(value).strip()

                if text and text.lower() not in {"nan", "none"}:
                    reasons.append(text)

    return reasons


def _generate_alerts_for_row(
    row: pd.Series,
    generated_at: datetime,
) -> List[dict]:
    """
    Generate zero or more alerts from one Risk Fusion row.

    All AI-related decisions are based on the current Phase 7 output.
    """
    alerts: List[dict] = []

    project_id = str(row["work_id"])

    risk_score = _decimal(row["risk_score"])
    risk_level = str(row["risk_level"]).upper()
    evidence_status = str(row["evidence_status"]).upper()

    # ---------------------------------------------------------------
    # Rule A — overall Risk Fusion level
    # ---------------------------------------------------------------

    if risk_level in {"HIGH", "CRITICAL"}:
        severity = _risk_level_severity(risk_level)

        reasons = _build_reasons(row)

        message = (
            f"This project has been assigned {risk_level} risk by the "
            f"Risk Fusion engine, with a risk score of {risk_score}."
        )

        if evidence_status:
            message += f" Evidence status: {evidence_status}."

        if reasons:
            message += " " + " ".join(reasons[:3])

        alerts.append(
            {
                "alert_id": f"{project_id}:overall_risk",
                "project_id": project_id,
                "alert_type": "high_risk_project",
                "severity": severity,
                "message": message,
                "sort_score": risk_score,
            }
        )

    # ---------------------------------------------------------------
    # Rule B — high-severity Risk Fusion signals
    # ---------------------------------------------------------------

    high_signal_count = int(
        _decimal(row["high_severity_signal_count"])
    )

    if high_signal_count > 0:
        reasons = _build_reasons(row)

        message = (
            f"This project contains {high_signal_count} high-severity "
            "signal(s) identified by the Risk Fusion engine."
        )

        if reasons:
            message += " " + " ".join(reasons[:3])

        alerts.append(
            {
                "alert_id": f"{project_id}:high_severity_signals",
                "project_id": project_id,
                "alert_type": "high_severity_signal",
                "severity": "high",
                "message": message,
                "sort_score": risk_score,
            }
        )

    # ---------------------------------------------------------------
    # Rule C — individual Risk Fusion domain signals
    # ---------------------------------------------------------------

    for column, alert_type, label in CONTRIBUTION_FIELDS:
        contribution = _decimal(row[column])

        # A contribution of zero means this domain did not contribute
        # to the final risk score.
        if contribution <= 0:
            continue

        cap = CONTRIBUTION_CAPS[column]

        # Contribution >= 75% of its domain's maximum is considered
        # a strong domain-level signal.
        strong_threshold = cap * Decimal("0.75")

        if contribution >= strong_threshold:
            severity = "critical" if contribution >= cap else "high"

            message = (
                f"{label} contributed {contribution} points to the "
                f"overall Risk Fusion score (domain cap: {cap}). "
                "This signal may warrant closer review."
            )

            alerts.append(
                {
                    "alert_id": f"{project_id}:{alert_type}",
                    "project_id": project_id,
                    "alert_type": alert_type,
                    "severity": severity,
                    "message": message,
                    "sort_score": risk_score,
                }
            )

    # ---------------------------------------------------------------
    # Rule D — insufficient/limited evidence
    # ---------------------------------------------------------------

    if evidence_status == "LIMITED":
        total_signals = int(
            _decimal(row["total_evidence_signals"])
        )

        message = (
            f"This project has limited AI evidence for risk assessment "
            f"({total_signals} evaluable signal(s)). Manual review may "
            "be appropriate before drawing conclusions."
        )

        alerts.append(
            {
                "alert_id": f"{project_id}:limited_evidence",
                "project_id": project_id,
                "alert_type": "limited_evidence",
                "severity": "medium",
                "message": message,
                "sort_score": risk_score,
            }
        )

    return alerts


# ---------------------------------------------------------------------
# GET /alerts
# ---------------------------------------------------------------------

@router.get("", response_model=List[AlertOut])
def list_alerts(
    skip: int = Query(default=0, ge=0),
    limit: int = Query(default=50, ge=1, le=100),
    db: Session = Depends(get_db),
):
    """
    Return advisory alerts generated from the current Phase 7
    Risk Fusion output.

    AI risk comes exclusively from:
        data/processed/project_risk_scores.csv

    The Project database is used only to confirm that the project exists.
    Legacy Phase-2 risk columns are not used.
    """

    generated_at = datetime.now(timezone.utc)

    risk_df = _load_risk_fusion()

    raw_alerts: List[dict] = []

    for _, row in risk_df.iterrows():
        raw_alerts.extend(
            _generate_alerts_for_row(
                row,
                generated_at,
            )
        )

    # ---------------------------------------------------------------
    # Deterministic ordering
    #
    # 1. severity
    # 2. overall Risk Fusion score descending
    # 3. project_id
    # 4. alert_type
    # ---------------------------------------------------------------

    raw_alerts.sort(
        key=lambda a: (
            SEVERITY_PRIORITY.get(a["severity"], 99),
            -a["sort_score"],
            a["project_id"],
            a["alert_type"],
        )
    )

    page = raw_alerts[skip: skip + limit]

    return [
        AlertOut(
            alert_id=a["alert_id"],
            project_id=a["project_id"],
            alert_type=a["alert_type"],
            severity=a["severity"],
            message=a["message"],
            created_at=generated_at,
        )
        for a in page
    ]