import React from 'react'
import {BarChart3,TrendingUp,Wallet} from 'lucide-react'
import {BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,LineChart,Line} from 'recharts'
import {projects,money} from '../data'
import {Section,Stat} from '../components/UI'
export default function Analytics(){
 const states=Object.entries(projects.reduce((a,p)=>{a[p.state]=(a[p.state]||0)+p.utilized;return a},{})).map(([state,utilized])=>({state:state.length>10?state.slice(0,9)+'…':state,utilized:Number((utilized/10000000).toFixed(2))})).slice(0,10)
 const trend=[{month:'Apr',value:42},{month:'May',value:49},{month:'Jun',value:57},{month:'Jul',value:64},{month:'Aug',value:71},{month:'Sep',value:76}]
 return <div className="p-4 md:p-8 max-w-[1400px] mx-auto"><div className="mb-6"><div className="eyebrow">Portfolio intelligence</div><h1 className="text-3xl font-extrabold mt-1">Analytics</h1><p className="text-slate-500 mt-1">Compare utilization, delivery and portfolio trends.</p></div>
 <div className="grid md:grid-cols-3 gap-4 mb-6"><Stat label="Average physical progress" value={`${Math.round(projects.reduce((a,p)=>a+p.physical,0)/projects.length)}%`} icon={TrendingUp}/><Stat label="Average financial progress" value={`${Math.round(projects.reduce((a,p)=>a+p.financial,0)/projects.length)}%`} icon={Wallet}/><Stat label="Delayed projects" value={projects.filter(p=>p.status==='Delayed').length} icon={BarChart3}/></div>
 <div className="grid lg:grid-cols-2 gap-5"><div className="card p-5"><Section title="Utilization by state" subtitle="₹ Crore, demo portfolio"/><div className="h-80"><ResponsiveContainer><BarChart data={states} layout="vertical"><CartesianGrid horizontal={false} strokeDasharray="3 3"/><XAxis type="number"/><YAxis dataKey="state" type="category" width={90}/><Tooltip/><Bar dataKey="utilized" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer></div></div><div className="card p-5"><Section title="Portfolio utilization trend" subtitle="Illustrative monthly trend"/><div className="h-80"><ResponsiveContainer><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis unit="%"/><Tooltip/><Line type="monotone" dataKey="value" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div></div>
 <div className="card mt-5 p-5"><Section title="How to use this view" subtitle="For the SIH demonstration"/><div className="grid md:grid-cols-3 gap-4 text-sm"><div className="rounded-xl bg-slate-50 p-4"><b>1. Detect</b><p className="text-slate-500 mt-1">Find states/categories with weaker progress or utilization.</p></div><div className="rounded-xl bg-slate-50 p-4"><b>2. Prioritize</b><p className="text-slate-500 mt-1">Open high-risk projects and inspect their evidence.</p></div><div className="rounded-xl bg-slate-50 p-4"><b>3. Verify</b><p className="text-slate-500 mt-1">Authorized officials validate the signal before action.</p></div></div></div>
 </div>
}