import React from 'react'
import {Link,useParams} from 'react-router-dom'
import {ArrowLeft, Building2, CalendarDays, IndianRupee, MapPin, ShieldAlert, Sparkles, Users} from 'lucide-react'
import {projects,money} from '../data'
import {RiskBadge,StatusBadge,Progress,Section} from '../components/UI'
export default function ProjectDetails(){
 const {id}=useParams(), p=projects.find(x=>x.id===id)||projects[0], riskScore={High:82,Medium:56,Low:21}[p.risk]
 return <div className="p-4 md:p-8 max-w-[1400px] mx-auto"><Link to="/projects" className="inline-flex items-center gap-2 text-sm text-slate-500 mb-5"><ArrowLeft size={15}/> Back to projects</Link>
 <div className="card p-6"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-5"><div><div className="eyebrow">{p.id} • {p.category}</div><h1 className="text-3xl font-extrabold mt-2">{p.name}</h1><div className="flex flex-wrap gap-4 text-sm text-slate-500 mt-3"><span className="inline-flex gap-1 items-center"><MapPin size={15}/>{p.district}, {p.state}</span><span className="inline-flex gap-1 items-center"><Users size={15}/>{p.constituency}</span><span className="inline-flex gap-1 items-center"><Building2 size={15}/>{p.agency}</span></div></div><div className="flex gap-2"><StatusBadge status={p.status}/><RiskBadge risk={p.risk}/></div></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-7"><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Sanctioned</div><div className="text-xl font-extrabold mt-1">{money(p.sanctioned)}</div></div><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Utilized</div><div className="text-xl font-extrabold mt-1">{money(p.utilized)}</div></div><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Physical progress</div><div className="mt-2"><Progress value={p.physical}/></div></div><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Financial progress</div><div className="mt-2"><Progress value={p.financial}/></div></div></div></div>
 <div className="grid lg:grid-cols-3 gap-5 mt-5"><div className="lg:col-span-2 space-y-5"><div className="card p-6"><Section title="Project timeline" subtitle="Milestone-oriented monitoring view"/><div className="relative pl-7 border-l-2 border-slate-200 space-y-7"><div><div className="absolute -left-[7px] h-3 w-3 rounded-full bg-navy"/><div className="text-xs text-slate-500">Start date</div><b>{p.start}</b><p className="text-sm text-slate-500 mt-1">Administrative initiation and work order phase.</p></div><div><div className="absolute -left-[7px] h-3 w-3 rounded-full bg-navy"/><div className="text-xs text-slate-500">Current snapshot</div><b>{p.updated}</b><p className="text-sm text-slate-500 mt-1">{p.physical}% physical progress and {p.financial}% financial progress recorded.</p></div><div><div className="absolute -left-[7px] h-3 w-3 rounded-full bg-slate-300"/><div className="text-xs text-slate-500">Expected completion</div><b>{p.due}</b><p className="text-sm text-slate-500 mt-1">Target completion date in demo dataset.</p></div></div></div>
 <div className="card p-6"><Section title="Financial & delivery notes"/><div className="grid sm:grid-cols-2 gap-5"><div><div className="text-sm text-slate-500">Utilization ratio</div><div className="text-2xl font-extrabold mt-1">{Math.round(p.utilized/p.sanctioned*100)}%</div></div><div><div className="text-sm text-slate-500">Progress gap</div><div className="text-2xl font-extrabold mt-1">{Math.abs(p.physical-p.financial)} pts</div></div></div></div></div>
 <div className="card p-6 h-fit"><div className="flex items-center gap-2 font-bold"><Sparkles className="text-navy" size={19}/> AI Risk Intelligence</div><p className="text-xs text-slate-500 mt-1">Advisory signal • human verification required</p><div className="mt-6 flex items-end justify-between"><div><div className="text-4xl font-extrabold">{riskScore}</div><div className="text-xs text-slate-500">risk score / 100</div></div><RiskBadge risk={p.risk}/></div><div className="h-3 bg-slate-100 rounded-full mt-4"><div className="h-full bg-navy rounded-full" style={{width:`${riskScore}%`}}/></div><div className="mt-6 space-y-3 text-sm"><div className="flex gap-2"><ShieldAlert size={17} className="text-rose-600 shrink-0"/><span>{p.risk==='High'?'Physical progress and schedule indicators need immediate review.':p.risk==='Medium'?'Project shows indicators worth monitoring against upcoming milestones.':'No major anomaly is visible in the current demo indicators.'}</span></div><div className="flex gap-2"><CalendarDays size={17} className="text-slate-500 shrink-0"/><span>Compare current progress with target milestones before taking action.</span></div><div className="flex gap-2"><IndianRupee size={17} className="text-slate-500 shrink-0"/><span>Check utilization alongside physical completion, not in isolation.</span></div></div><div className="mt-6 rounded-xl bg-amber-50 border border-amber-100 p-3 text-xs text-amber-800">AI-generated information is advisory. Final decisions, verification and official action remain with authorized authorities.</div></div></div>
 </div>
}