import React,{useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {Eye, Filter, Search, SlidersHorizontal} from 'lucide-react'
import {projects, money} from '../data'
import {RiskBadge,StatusBadge,Progress} from '../components/UI'
export default function Projects(){
 const [q,setQ]=useState(''),[status,setStatus]=useState('All'),[risk,setRisk]=useState('All'),[category,setCategory]=useState('All')
 const filtered=useMemo(()=>projects.filter(p=>(`${p.id} ${p.name} ${p.state} ${p.district} ${p.constituency}`.toLowerCase().includes(q.toLowerCase()))&&(status==='All'||p.status===status)&&(risk==='All'||p.risk===risk)&&(category==='All'||p.category===category)),[q,status,risk,category])
 const cats=[...new Set(projects.map(p=>p.category))]
 return <div className="p-4 md:p-8 max-w-[1500px] mx-auto"><div className="mb-6"><div className="eyebrow">Portfolio explorer</div><h1 className="text-3xl font-extrabold mt-1">Projects</h1><p className="text-slate-500 mt-1">Search, filter and open a complete project intelligence view.</p></div>
 <div className="card p-4 mb-5"><div className="grid md:grid-cols-5 gap-3"><div className="md:col-span-2 relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search project, state, district..." className="w-full border border-slate-200 rounded-xl py-2.5 pl-10 pr-3"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="border border-slate-200 rounded-xl px-3"><option>All</option><option>Ongoing</option><option>Completed</option><option>Delayed</option></select><select value={risk} onChange={e=>setRisk(e.target.value)} className="border border-slate-200 rounded-xl px-3"><option>All</option><option>High</option><option>Medium</option><option>Low</option></select><select value={category} onChange={e=>setCategory(e.target.value)} className="border border-slate-200 rounded-xl px-3"><option>All</option>{cats.map(c=><option key={c}>{c}</option>)}</select></div></div>
 <div className="card overflow-hidden"><div className="p-4 border-b border-slate-200 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-semibold"><SlidersHorizontal size={17}/> {filtered.length} projects matched</div><div className="text-xs text-slate-500">Demo data</div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500 uppercase"><tr>{['Project','Location','Category','Financial','Physical','Status','Risk',''].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-4 py-4 min-w-[260px]"><div className="font-bold">{p.name}</div><div className="text-xs text-slate-500 mt-1">{p.id}</div></td><td className="px-4 py-4 min-w-[150px]">{p.district}<div className="text-xs text-slate-500">{p.state}</div></td><td className="px-4 py-4 whitespace-nowrap">{p.category}</td><td className="px-4 py-4 min-w-[130px]"><div className="text-xs text-slate-500 mb-1">{money(p.utilized)} / {money(p.sanctioned)}</div><Progress value={p.financial}/></td><td className="px-4 py-4 min-w-[110px]"><Progress value={p.physical}/></td><td className="px-4 py-4"><StatusBadge status={p.status}/></td><td className="px-4 py-4"><RiskBadge risk={p.risk}/></td><td className="px-4 py-4"><Link to={`/projects/${p.id}`} className="h-9 w-9 rounded-lg border border-slate-200 inline-flex items-center justify-center text-navy"><Eye size={16}/></Link></td></tr>)}</tbody></table>{filtered.length===0&&<div className="p-10 text-center text-slate-500">No projects match these filters.</div>}</div></div>
 </div>
}