import { toNumber } from './formatters'

/**
 * Shared, pure display model for the Risk Fusion + Explainable AI UI.
 *
 * ============================================================================
 * THE ONE RULE THIS FILE EXISTS TO ENFORCE
 * ============================================================================
 * The backend is the single source of truth for every risk number. Nothing in
 * this file computes, re-weights, or re-derives a risk score. It only:
 *
 *   - reshapes `GET /projects/:id/risk` into an array the UI can map over,
 *   - computes DISPLAY-ONLY ratios (share of final risk, bar widths),
 *   - reports whether the backend's own numbers reconcile.
 *
 * Three distinct quantities are kept strictly separate everywhere, because
 * conflating them is the single easiest way to make an explanation wrong:
 *
 *   rawScore     -- the component's own 0-100 detector score.
 *   weight       -- the component's configured point cap out of 100
 *                   (ml/risk_config.py RISK_COMPONENT_CAPS). Because the caps
 *                   sum to exactly 100, the cap in points equals the weight in
 *                   percent -- that is a property of the config, not an
 *                   assumption made here.
 *   contribution -- the points this component actually added to the final
 *                   score. By the backend's construction,
 *                   rawScore * weight / 100 === contribution.
 *   sharePct     -- DISPLAY ONLY: contribution / total contribution. This is
 *                   the only number this file invents, and it never feeds back
 *                   into the score.
 */

// Display order: highest configured weight first, so the component that CAN
// matter most is read first. Names are the backend's own component keys.
export const COMPONENT_ORDER = [
  'compliance',
  'financial_anomaly',
  'timeline_anomaly',
  'duplicate',
  'payment',
  'isolation_forest',
  'data_quality',
]

// Fallback labels only. The backend sends `label` on every component; these
// are used purely so a malformed/partial payload still renders something
// readable instead of a raw snake_case key.
export const FALLBACK_COMPONENT_LABELS = {
  compliance: 'Compliance Risk',
  financial_anomaly: 'Financial Anomaly Risk',
  timeline_anomaly: 'Timeline Anomaly Risk',
  duplicate: 'Duplicate / Similar Work Risk',
  payment: 'Payment Pattern Risk',
  isolation_forest: 'ML Anomaly Risk (Isolation Forest)',
  data_quality: 'Data Quality Risk',
}

// Severity tone. Every use site MUST pair these with the status text and the
// numeric score -- colour alone never carries meaning (accessibility, and
// because "orange" is not an explanation).
export const STATUS_TONE = {
  HIGH: { color: '#c0392b', bg: '#fadcd8', label: 'HIGH' },
  MEDIUM: { color: '#b7791f', bg: '#fbf0de', label: 'MEDIUM' },
  LOW: { color: '#1b8a5a', bg: '#e7f4ec', label: 'LOW' },
  NONE: { color: '#55636e', bg: '#eef1f3', label: 'NOT TRIGGERED' },
}

export function statusTone(status) {
  return STATUS_TONE[String(status || 'NONE').toUpperCase()] || STATUS_TONE.NONE
}

// Tooltip copy for the vocabulary the page uses. Kept here so the same term
// never gets two different definitions on two different panels.
export const GLOSSARY = {
  risk_score:
    'The final fused review-priority score out of 100, produced by the backend Risk Fusion engine. It is a prioritisation signal, not a finding of wrongdoing.',
  raw_score:
    'The risk/anomaly score generated by this individual detection component on its own, before fusion, expressed out of 100.',
  weight:
    'The configured importance of this evidence source in the existing Risk Fusion model, as a share of the 100-point scale. Set in ml/risk_config.py; the seven weights sum to exactly 100.',
  contribution:
    'The number of risk points this component actually contributed to the final fused score. Equals raw score x weight / 100.',
  share:
    'Display only: this component\u2019s contribution as a percentage of the total contributed points. Not the same as its weight.',
  risk_fusion:
    'The backend step that combines every independent evidence source into one capped, weighted score. The frontend visualises this result and never recalculates it.',
  compliance:
    'Deterministic checks against documented MPLADS rules. A flag means an explicit written rule condition was met.',
  financial_anomaly:
    'Peer-relative statistical comparison of this project\u2019s amounts against comparable projects.',
  timeline_anomaly:
    'Peer-relative statistical comparison of this project\u2019s durations against comparable projects.',
  duplicate:
    'Similar-work detection across the dataset, weighted down when the matching description is common boilerplate.',
  payment:
    'Analysis of the recorded payment transactions for this project relative to its peer baseline.',
  isolation_forest:
    'Unsupervised multivariate outlier detection over the engineered feature set. Flags unusual combinations of values, even when no single field is unusual.',
  data_quality:
    'Source/field conflicts in the underlying records. Describes data-collection inconsistency, not project behaviour.',
  evidence_status:
    'How much of the evidence base could actually be evaluated for this project: SUFFICIENT, LIMITED or INSUFFICIENT.',
}

// The six evidence domains the backend reports evaluability for, in the exact
// label strings ml/risk_config.py's DATA_QUALITY_DOMAIN_LABELS emits. The API
// returns only the domains that could NOT be evaluated, so the available ones
// are this list minus those.
export const DATA_QUALITY_DOMAINS = [
  'Compliance data',
  'Financial anomaly data',
  'Timeline anomaly data',
  'Duplicate/similarity data',
  'Payment pattern data',
  'Statistical outlier (Isolation Forest) data',
]

// Evidence keys that are explanatory prose rather than a display fact.
export const NOTE_EVIDENCE_KEYS = new Set([
  'review_note',
  'peer_comparison_note',
  'evidence_note',
  'note',
])

// Cosmetic relabelling of raw evidence-dict keys. Values are never altered.
export const EVIDENCE_KEY_LABELS = {
  metric: 'Metric',
  metric_label: 'Metric',
  observed_display: 'Observed value',
  observed_value: 'Observed value',
  direction: 'Direction',
  modified_z_score: 'Modified z-score',
  decision_method: 'Detection method',
  peer_group_level: 'Peer group',
  peer_group_key: 'Peer group key',
  peer_group_size: 'Comparable projects',
  peer_median: 'Peer median',
  peer_median_display: 'Peer median',
  peer_deviation_pct: 'Deviation from peer median',
  matched_work_id: 'Matched work ID',
  match_type: 'Match type',
  similarity_score: 'Similarity',
  description_frequency: 'Description also seen in',
  rule_id: 'Rule',
  category: 'Category',
  severity: 'Severity',
  family: 'Signal family',
  signal: 'Signal',
  method: 'Detection method',
  strength: 'Strength',
  value: 'Observed value',
  interpretation: 'Interpretation',
  observed_feature_count: 'Features observed',
}

export function evidenceKeyLabel(key) {
  return EVIDENCE_KEY_LABELS[key] || String(key).replace(/_/g, ' ')
}

export function formatEvidenceValue(key, value) {
  if (value === null || value === undefined) return null
  if (key === 'similarity_score' && typeof value === 'number') {
    return `${Math.round(value * 100)}%`
  }
  if (key === 'peer_deviation_pct' && typeof value === 'number') {
    return `${value > 0 ? '+' : ''}${value}%`
  }
  if (key === 'description_frequency' && typeof value === 'number') {
    return `${value} other project description(s)`
  }
  if (key === 'modified_z_score' && typeof value === 'number') {
    return value.toFixed(2)
  }
  if (typeof value === 'boolean') return value ? 'Yes' : 'No'
  return String(value)
}

/**
 * Reshape one backend risk payload into the display model.
 *
 * Returns null when there is no payload at all, so callers can distinguish
 * "no data" from "data that happens to be clean".
 */
export function buildRiskModel(risk) {
  if (!risk || typeof risk !== 'object') return null

  const rawComponents =
    risk.components && typeof risk.components === 'object' ? risk.components : {}

  // Anything the backend sends that isn't in COMPONENT_ORDER is still shown,
  // appended after the known ones, so a future component never goes missing.
  const knownFirst = COMPONENT_ORDER.filter(name => rawComponents[name])
  const extras = Object.keys(rawComponents).filter(
    name => !COMPONENT_ORDER.includes(name)
  )

  const components = [...knownFirst, ...extras].map(name => {
    const detail = rawComponents[name] || {}
    const weight = toNumber(detail.weight) ?? 0
    const contribution = toNumber(detail.contribution) ?? 0

    // Prefer the backend's own raw score. Only if it is absent do we invert
    // the backend's own identity (contribution / weight * 100) -- which is a
    // restatement of its number, not a new calculation.
    const rawScore =
      toNumber(detail.score) ?? (weight > 0 ? (contribution / weight) * 100 : 0)

    const status = String(detail.status || 'NONE').toUpperCase()

    return {
      name,
      label: detail.label || FALLBACK_COMPONENT_LABELS[name] || name,
      description: detail.description || GLOSSARY[name] || '',
      rawScore,
      weight,
      contribution,
      status,
      triggered: status !== 'NONE',
      reasons: Array.isArray(detail.reasons) ? detail.reasons.filter(Boolean) : [],
      evidence: Array.isArray(detail.evidence) ? detail.evidence : [],
      // False only when the breakdown was rebuilt from a legacy processed CSV
      // that predates the structured-evidence column.
      evidenceAvailable: detail.evidence_available !== false,
      reviewActions: Array.isArray(detail.review_actions)
        ? detail.review_actions.filter(Boolean)
        : [],
    }
  })

  const totalContribution = components.reduce((sum, c) => sum + c.contribution, 0)
  const maxContribution = components.reduce((max, c) => Math.max(max, c.contribution), 0)

  const withDisplayRatios = components.map(c => ({
    ...c,
    // DISPLAY ONLY -- share of the points actually contributed.
    sharePct: totalContribution > 0 ? (c.contribution / totalContribution) * 100 : 0,
    // DISPLAY ONLY -- bar length proportional to actual contribution, so the
    // longest bar is always the biggest real contributor (brief section 9).
    barPct: maxContribution > 0 ? (c.contribution / maxContribution) * 100 : 0,
    // DISPLAY ONLY -- how much of this component's own cap was used.
    capFillPct: c.weight > 0 ? Math.min(100, (c.contribution / c.weight) * 100) : 0,
  }))

  const score = toNumber(risk.risk_score ?? risk.riskScore)
  const level = String(risk.risk_level ?? risk.riskLevel ?? '').toUpperCase() || null

  const triggered = withDisplayRatios
    .filter(c => c.triggered)
    .sort((a, b) => b.contribution - a.contribution)

  const notTriggered = withDisplayRatios.filter(c => !c.triggered)

  // Does the backend's own arithmetic add up? If it ever doesn't, the UI says
  // so out loud rather than quietly showing bars that don't match the score.
  const reconciles =
    score === null || components.length === 0
      ? null
      : Math.abs(totalContribution - score) <= 0.1

  return {
    workId: risk.work_id ?? risk.workId ?? null,
    score,
    level,
    evidenceStatus: String(risk.evidence_status ?? '').toUpperCase() || null,
    hasComponents: components.length > 0,
    components: withDisplayRatios,
    triggered,
    notTriggered,
    totalContribution,
    reconciles,
    totalSignals: toNumber(risk.total_evidence_signals) ?? triggered.length,
    highSeverityCount: toNumber(risk.high_severity_signal_count) ?? 0,
    // Legacy flat reason list -- preserved so the WHY FLAGGED panel still has
    // something real to show even if `components` is unavailable.
    legacyReasons: Array.isArray(risk.risk_reasons)
      ? risk.risk_reasons.filter(Boolean)
      : Array.isArray(risk.reasons)
        ? risk.reasons.filter(Boolean)
        : [],
    dataQuality: buildDataQuality(risk),
  }
}

/**
 * Per-domain data-quality view.
 *
 * Critical distinction (brief section 14): "no anomaly detected" and "could
 * not be evaluated" are different states and must never render the same. When
 * the backend did not record per-domain detail at all, `evaluable` is null
 * (unknown) rather than being optimistically defaulted to true.
 */
export function buildDataQuality(risk) {
  const detailAvailable = risk?.data_quality_detail_available !== false
  const unevaluable = Array.isArray(risk?.data_quality_notes)
    ? risk.data_quality_notes
    : []

  const domains = DATA_QUALITY_DOMAINS.map(label => ({
    label,
    evaluable: detailAvailable ? !unevaluable.includes(label) : null,
  }))

  return {
    detailAvailable,
    unevaluable,
    domains,
    complete: detailAvailable && unevaluable.length === 0,
    evidenceStatus: String(risk?.evidence_status ?? '').toUpperCase() || null,
  }
}

/**
 * Pull real peer-comparison rows out of the per-signal evidence dicts.
 *
 * Only evidence the backend actually emitted is used -- no peer group is
 * invented, and a metric with no peer data simply produces no row (the UI
 * then states that peer comparison is unavailable for it).
 *
 * Note on deviation %: ml/risk.py deliberately omits `peer_deviation_pct`
 * when the peer statistics sit on a log-transformed scale, because a
 * percentage would be mathematically meaningless there. That omission is
 * respected -- the z-score is shown instead, never a substitute percentage.
 */
export function extractPeerComparisons(components = []) {
  const rows = []

  components.forEach(component => {
    component.evidence.forEach((evidence, index) => {
      if (!evidence || typeof evidence !== 'object') return

      const hasPeerData =
        evidence.peer_group_size !== undefined ||
        evidence.peer_median_display !== undefined ||
        evidence.peer_median !== undefined

      if (!hasPeerData) return

      rows.push({
        key: `${component.name}-${index}`,
        componentLabel: component.label,
        metric: evidence.metric_label || evidence.metric || 'Metric',
        observed: evidence.observed_display ?? evidence.observed_value ?? null,
        peerMedian: evidence.peer_median_display ?? evidence.peer_median ?? null,
        deviationPct: toNumber(evidence.peer_deviation_pct),
        zScore: toNumber(evidence.modified_z_score),
        groupLevel: evidence.peer_group_level || null,
        groupKey: evidence.peer_group_key || null,
        groupSize: toNumber(evidence.peer_group_size),
        note: evidence.peer_comparison_note || null,
      })
    })
  })

  return rows
}

/**
 * Peer-group criteria chips, taken from the peer group the backend actually
 * used. `peer_group_level` names the grouping (e.g. state_work_category) and
 * `peer_group_key` carries its pipe-separated values.
 */
export function peerCriteria(rows = []) {
  const criteria = new Set()

  rows.forEach(row => {
    if (row.groupLevel) {
      criteria.add(String(row.groupLevel).replace(/_/g, ' '))
    }
    if (row.groupKey) {
      String(row.groupKey)
        .split('|')
        .map(part => part.trim())
        .filter(Boolean)
        .forEach(part => criteria.add(part))
    }
  })

  return [...criteria]
}

/**
 * Reviewer checklist, ordered by how much each triggered component actually
 * contributed -- so the biggest driver is reviewed first.
 *
 * These are review SUGGESTIONS sourced from ml/risk_config.py, tied to the
 * category of signal. They are never conclusions and never assert anything
 * about this specific project's records.
 */
export function buildReviewChecklist(triggeredComponents = []) {
  const seen = new Set()
  const checklist = []

  triggeredComponents.forEach(component => {
    component.reviewActions.forEach(action => {
      if (seen.has(action)) return
      seen.add(action)
      checklist.push({ action, componentLabel: component.label })
    })
  })

  return checklist
}

/** Sentence describing the overall level, in responsible-AI language. */
export function levelNarrative(level, signalCount) {
  const count =
    signalCount && signalCount > 0 ? `${signalCount} risk signal(s) were detected` : 'Risk signals'

  switch (String(level || '').toUpperCase()) {
    case 'CRITICAL':
      return `${count} across multiple independent evidence sources. Prioritise this project for human review.`
    case 'HIGH':
      return `${count} and warrant review before further disbursement.`
    case 'MEDIUM':
      return `${count} that require human review against upcoming milestones.`
    case 'LOW':
      return 'No strong risk signal is visible in the evidence that could be evaluated for this project.'
    default:
      return 'A risk level is not available for this project.'
  }
}